ymyzk/mypy-playground

app/static/index.js
app/views/index.html

Add "Gist" button

---

app/static/index.js

Stop using XMLHttpRequest directly

---

app/static/index.js

Add feature to fetch a gist

---

app/views/index.html

- Update jQuery
- Update Ace
- Use CDN for axios

Update front-end libraries

---

app/mypy_playground/sandbox.py

Use --no-site-packages by default

---

app/Dockerfile
app/Pipfile
app/Pipfile.lock
app/requirements.txt
sandbox/Pipfile
sandbox/Pipfile.lock

Use Python 3.7

---

app/mypy_playground/sandbox.py

Add --warn-unreachable option

---

.github/workflows/ci.yml
app/Dockerfile
app/Dockerfile-prod
app/mypy.ini

Run app on Python 3.8

---

app/mypy_playground/sandbox/base.py

Add --show-error-codes option

---

sandbox/0.902/Dockerfile
sandbox/0.902/requirements.in
sandbox/0.902/requirements.txt

Add mypy 0.902 and update 0.910

---

app/mypy_playground/sandbox/base.py

Add Python 3.10 to version option

---

app/mypy_playground/sandbox/base.py

https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-strict-equality

add "strict-equality" flag

---

app/frontend/src/Result.jsx

fix fetched_gist message

---

app/frontend/src/utils.js
app/frontend/test/utils_test.js

Annotate errors correctly when --show-column-numbers is enabled

---

app/frontend/src/App.jsx
app/frontend/src/ContextLoader.jsx
app/frontend/src/Header.jsx
app/frontend/src/index.jsx
app/frontend/src/template.ejs
app/mypy_playground/app.py
app/mypy_playground/handlers.py

Remove a bit hacky code to inject initial context using a template engine and use API + React instead.

Improve context loading

---

app/mypy_playground/sandbox/base.py

Add missing options `version` and `show-traceback`

---

app/mypy_playground/handlers.py
app/mypy_playground/sandbox/base.py

But keep 3.10 as the default selection
Resolves #198

Add python 3.11 option

---

.github/workflows/deploy-gcp.yml
sandbox/README.md
sandbox/cloud_functions/deploy.sh

Use Python 3.10 for Cloud Functions sandbox by default

---

app/frontend/components/App.tsx

Fix bugs introduced in Next.js migration

---

app/frontend/src/App.css

500px -> 560px
- resolves #185

(🎁) make the options modal wider

---

.github/workflows/deploy-gcp.yml

Deploy mypy master branch to Cloud Functions everyday

---

app/mypy_playground/sandbox/base.py

* Add --new-type-inference option #392 
* Replace --no-implicit-optional option with --implicit-optional as the default value is changed #387

Modernize list of options

---

app/frontend/package-lock.json

Update frontend dependencies to prepare for the upgrade from Node.js v18 to v20.

Update frontend dependencies

---

.github/workflows/ci.yml
app/Dockerfile-prod
app/frontend/Dockerfile
app/frontend/jest.setup.js
app/frontend/package-lock.json
app/frontend/package.json

Upgrade frontend build environment to Node.js v20

Upgrade frontend build environment to Node.js v20

---

.github/workflows/ci.yml

- Use push trigger only for the master branch
- Fix if statements for the Docker image job (fix for #491)
- CI runs when PR is created or a new commit is pushed to the master branch
- The `build_docker_images` job only runs when the master branch is updated

Fix and polish CI config

---

app/frontend/components/App.tsx
app/frontend/components/Header.tsx
app/frontend/components/MultiSelectOption.tsx
app/frontend/package-lock.json
app/frontend/package.json
app/frontend/tsconfig.json
app/mypy_playground/handlers.py
app/mypy_playground/sandbox/base.py
app/mypy_playground/sandbox/cloud_functions.py
app/mypy_playground/sandbox/docker.py

Implemented a feature requested in #465.
1. mypy Playground shows the `--enable-incomplete-features` flag/option under the "Options" button.
2. It provides `TypeVarTuple` and `Unpack` as choices.
3. Users can select multiple choices at the same time and run mypy.

Enable incomplete feature

---

.github/workflows/ci.yml
app/frontend/.prettierrc
app/frontend/components/App.tsx
app/frontend/components/ContextLoader.tsx
app/frontend/components/Editor.module.css
app/frontend/components/Editor.tsx
app/frontend/components/Header.module.css
app/frontend/components/Header.tsx
app/frontend/components/MultiSelectOption.tsx
app/frontend/components/Result.module.css
app/frontend/components/Result.test.tsx
app/frontend/components/Result.tsx
app/frontend/jest.config.js
app/frontend/jest.setup.js
app/frontend/next.config.js
app/frontend/package-lock.json
app/frontend/package.json
app/frontend/pages/_app.tsx
app/frontend/pages/index.tsx
app/frontend/styles/globals.css
app/frontend/utils/api.ts
app/frontend/utils/gist.ts
app/frontend/utils/utils.test.ts
app/frontend/utils/utils.ts

Introduce Prettier for auto-formatting frontend code.
- CI runs the prettier check
- Existing code passes the prettier check

Introduce Prettier

---

app/frontend/components/App.tsx
app/frontend/components/Header.tsx
app/frontend/components/types.tsx
app/mypy_playground/handlers.py

Use more precise types in frontend TypeScript code.

Use more precise types in frontend code

---

.github/workflows/ci.yml

Upgrade actions/download-artifact and actions upload-artifact to v4.
CI keeps working.

Upgrade actions/{download,upload}-artifact to v4

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/tsconfig.json

Upgrade prettier to 3.2.4.
No errors in CI.

Upgrade prettier to 3.2.4

---

app/frontend/pages/index.tsx

Add `<link rel="canonical" href="/" />` for better SEO.
The tag is added to the top page.

Add <link rel="canonical" href="/" /> for SEO

---

app/mypy_playground/sandbox/base.py

Add `--enable-incomplete-feature` PreciseTupleTypes and NewGenericSyntax

---

.github/workflows/ci.yml
app/Dockerfile-prod
app/frontend/Dockerfile

Upgrade Node.js used for the frontend from v20 to v22.

Upgrade Node.js to v22

---

.pre-commit-config.yaml
app/mypy_playground/handlers.py
app/mypy_playground/prometheus.py
app/mypy_playground/sandbox/__init__.py
app/mypy_playground/sandbox/base.py
app/mypy_playground/sandbox/cloud_functions.py
app/mypy_playground/sandbox/docker.py
app/mypy_playground/utils.py
app/pyproject.toml
app/tests/sandbox/test_docker.py
app/tests/test_app.py
app/tests/test_prometheus.py
app/tests/test_utils.py

- Upgraded the pre-commit hooks
- Updated the pre-commit hooks and ruff config to detect and fix more variety of errors automatically.

Upgrade pre-commit hooks and fix existing code

---

.github/dependabot.yml

Fix dependabot config for pip package ecosystem.
Dependabot will upgrade pip dependencies.

Fix Dependabot working directory for pip dependencies

---

.github/workflows/check-new-version.yml

This is the first attempt to detect new mypy releases automatically using GitHub Actions, and create a MR for an update.
When the new workflow is executed manually, it will check newer mypy releases and create a PR for an upgrade.

Attempt to detect new mypy releases automatically using CI
